using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using RizgarOzan.TmpGlyphAudit;
using RizgarOzan.TmpGlyphAudit.Editor;
using TMPro;
using UnityEditor;
using UnityEngine;
using UnityEngine.TestTools;
using UnityEngine.TextCore.LowLevel;

public class GlyphAuditTests
{
    // Generated by tools/make_test_font.py: glyphs for " ABCğ" and nothing else.
    static Font TestFont => AssetDatabase.LoadAssetAtPath<Font>(
        "Packages/com.rizgarozan.tmp-glyph-audit/Tests/Editor/Fonts/GlyphAuditTest.ttf");
    const uint Kanji = 0x6F22; // 漢

    readonly List<Object> _created = new List<Object>();

    [TearDown]
    public void TearDown()
    {
        foreach (var o in _created) if (o != null) Object.DestroyImmediate(o);
        _created.Clear();
    }

    TMP_FontAsset Dynamic()
    {
        var font = TMP_FontAsset.CreateFontAsset(TestFont, 36, 4, GlyphRenderMode.SDFAA, 256, 256);
        Assert.IsNotNull(font, "could not create a font asset from the test font");
        _created.Add(font);
        return font;
    }

    TMP_FontAsset StaticWith(string characters)
    {
        var font = Dynamic();
        font.TryAddCharacters(characters);
        font.atlasPopulationMode = AtlasPopulationMode.Static;
        return font;
    }

    [Test]
    public void Dynamic_font_has_what_its_source_file_has_without_growing_the_atlas()
    {
        var font = Dynamic();
        int before = font.characterTable.Count;
        var source = TmpFontSource.For(font, new Dictionary<TMP_FontAsset, TmpFontSource>());

        Assert.IsTrue(source.HasGlyph('ğ'));
        Assert.IsTrue(source.HasGlyph('A'));
        Assert.IsFalse(source.HasGlyph(Kanji));
        Assert.AreEqual(before, font.characterTable.Count, "the audit must not add characters to the atlas");
    }

    [Test]
    public void Static_font_has_only_its_character_table()
    {
        var source = TmpFontSource.For(StaticWith("AB"), new Dictionary<TMP_FontAsset, TmpFontSource>());
        Assert.IsTrue(source.HasGlyph('A'));
        Assert.IsFalse(source.HasGlyph('C'));
    }

    [Test]
    public void Fallback_font_assets_are_searched()
    {
        var main = StaticWith("AB");
        main.fallbackFontAssetTable = new List<TMP_FontAsset> { StaticWith("C") };
        var audit = new GlyphAudit();
        audit.Check("ABC", main, true, true, "test", "fallback");
        // Not 'D': the project's TMP Settings default font would supply it, as it does at runtime.
        audit.Check("ABC漢", main, true, true, "test", "missing kanji");
        Assert.AreEqual(1, audit.Report.Findings.Count);
        Assert.AreEqual(new[] { Kanji }, audit.Report.Findings[0].Missing.ToArray());
    }

    [Test]
    public void Font_tag_text_is_reported_under_the_font_the_tag_loads()
    {
        // unity/ has TMP Essential Resources: LiberationSans SDF sits in Resources/Fonts & Materials.
        var main = StaticWith("AB");
        var audit = new GlyphAudit();
        audit.Check("AB<font=\"LiberationSans SDF\">漢</font>", main, true, true, "test", "known font");
        audit.Check("<font=\"No Such Font\">漢", main, true, true, "test", "unknown font");

        Assert.AreEqual(2, audit.Report.Findings.Count);
        StringAssert.EndsWith("LiberationSans SDF.asset", audit.Report.Findings[0].Font);
        Assert.AreEqual(new[] { Kanji }, audit.Report.Findings[0].Missing.ToArray());
        // TMP cannot load the font, so it draws the tag as text in the text's own font.
        Assert.AreEqual(main.name, audit.Report.Findings[1].Font);
        Assert.AreEqual(new[] { Kanji }, audit.Report.Findings[1].Missing.ToArray());
    }

    [Test]
    public void Text_components_are_found_with_their_hierarchy_path()
    {
        LogAssert.ignoreFailingMessages = true; // TMP may complain about missing TMP Settings in a bare project
        var root = new GameObject("Menu");
        _created.Add(root);
        var child = new GameObject("Title");
        child.transform.SetParent(root.transform);
        var text = child.AddComponent<TextMeshPro>();
        text.font = Dynamic();
        text.text = "<b>ABCğ</b> 漢";

        var audit = new GlyphAudit();
        audit.ScanObject(root, "Assets/Menu.unity");

        Assert.AreEqual(1, audit.Report.TextsScanned);
        var finding = audit.Report.Findings.Single();
        Assert.AreEqual("Menu/Title", finding.Location);
        Assert.AreEqual(new[] { Kanji }, finding.Missing.ToArray());
    }
}
